### ISSUE TITLE
Model Choosing UI returns in 403 Error

### ISSUE THREAD

**Issue by HakaKZ** [etherealxx/volatile-concentration-localux-colab#1]
Upon running the main cell and waited for about a minute where you're supposed UI to choose the model, the output panel shows a google 403 error without any explanation.

![image](https://user-images.githubusercontent.com/132117466/235280590-e93c64d2-a0eb-48ed-bd6c-86f1b55a3abb.png)

Steps to recreate the issue:
1. Run the model in stable with "choose_models" ticked and with (or without) "controlnet_models" ticked.
2. That's it...

**Comment by etherealxx** [comment]
@HakaKZ Hi👋
What browser did you use? Is it Chrome? I noticed this problem too on Bromite browser (android), but it runs fine on Chrome.

**Comment by HakaKZ** [comment]
Hello, sorry it took time for me to answer
I receive this issue in Chrome and Brave.
At first, it thought it's because of the Brave browser so i log in using Google Chrome but it outputs the same 403 error.

**Comment by etherealxx** [comment]
@HakaKZ Sorry for the late response.
At first i thought this only happens on some browser with enhanced security, or maybe some old chrome browser. But the fact that you also happens to encounter this problem is quite baffling.
It is possible that you might use vpt, dns, proxy, adblocker or other network related things.

But in the end, i think i'll abandon this project. It was made to simplify things, not to overly complicate users with random incompatibilities.

However, if you might know the root of the problem, feel free to reach👋

**Comment by HakaKZ** [comment]
Hi again.. there's something i think worth to mention around..
I'm not sure if you will discontinue or not but i need to mention that the UI works well if you're not ticking the "Choose model" and "Controlnet model", hence leaving it with only the SD1.5 model.

But i think it's kinda okay since you can get around it by using the added CivitAI downloader addon and you can download other models there (minus models that are not available from HuggingFace).

Other than that, i don't think i can find the source of the problem on the 403 error
but i do having an idea of "download the model directly to/from repository without having to choose". But i will only leave this as an idea as the model are still usable and can still works fine without the warning.

**Comment by etherealxx** [comment]
> the UI works well if you're not ticking the "Choose model" and "Controlnet model", hence leaving it with only the SD1.5 model.

That destroys the whole purpose of this colab. At that point just use camenduru's colab.
Also, afaik you're the only person who met this exact problem on PC. (i know this problem on bromite browser but not the others)

And, other people make better colab with same 'bypass' system like linaqruf's, machiavel's, demu's, nocrypt's, nolan's, etc.

**Comment by HakaKZ** [comment]
I'm sorry for asking this but
Can you provide me with links to their colabs?
I haven't gone too deep around the SDUI Colab community yet..

**Comment by etherealxx** [comment]
btw for you @HakaKZ and other people potentially have the same problem, please report it here https://github.com/gradio-app/gradio/issues/4077

**Comment by HakaKZ** [comment]
Hello again, it's me
I have figure out the problem on the 403 error.
The problem appears when you have your browser cookies setting blocking these two cookies. These two, as far as i inspect are basically the third-party UI site that used to choose your model on the localhost section. Having my cookies unblocked (Allow cookies) allowing me to see the UI without the 403 error.. so it's basically the Cookies error..

![image](https://user-images.githubusercontent.com/132117466/236627372-ef112563-4ed8-4f0f-a4da-f6f70c706e11.png)

Sorry for taking your time to figure out the problem thus far, and thank you for providing this colab and helping me to figure this problem despite numbers of confusion.

**Comment by etherealxx** [comment]
> Sorry for taking your time to figure out the problem thus far

Nah i should be the one who thanks you, since not only you that encountered this problem. I also figured out that if i allow cookies on colab website on Bromite, it also works. yeah so it's a cookie thing. I won't know about this if it's not bcoz of you😋 I'll point this out on the readme page.

The thing that bugged me though, why those cookies blocked on some people's browser, while others don't🤔
