### ISSUE TITLE
"Warning, You might be executing code that is disallowed..." popup colab

### ISSUE THREAD

**Issue by baiker9999** [etherealxx/volatile-concentration-localux-colab#11]
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/138266623/14ae3564-16d7-4e23-9820-9333892eb58a)

What strings are they blocking now?
If this keeps up, you may have to migrate to alternative computing platforms.

At a glance, there are "stable diffusion" string variants, like "filename": "stable_diffusion_1_5_webui_colab.ipynb"
or "...volatile-concentration-localux/repositories/stable-diffusion-stability-ai/ldm/util.py..."

**Comment by eyetest42** [comment]
can confirm that this is happening to me too

**Comment by basedholychad** [comment]
can i ask how you guys choosing a1111 tagcomplete and composable lora as default? i'm using stable line and still need to manual check on extensions tab and download 2 of them manual and then reset the webui to use them

**Comment by etherealxx** [comment]
@baiker9999 @eyetest42 Hi👋
Have you guys use the latest, latest version available? The July 2 one? (look at the small text below the title). Here's the link (still the same link): https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/54b31704-82e6-43bb-9491-06ec5563f2e9)


For the record, they're now blocking `sd-webui` string, which i use for excluding `sd-webui-tunnel` extension so that it can't be disabled. They also blocks the Base64 encoded version of that string, which is nuts. In the updated code, i use Base58 instead😋

**Comment by etherealxx** [comment]
@basedholychad you need to manually checks it since it's an additional extension that i adds myself (after some request by several people). Camenduru's colab doesn't have that so i disable it by default. Though i don't quite understand why you need to manually install it and reset UI, since it works fine on me, preinstalled after i checked the box on the extension selection earlier. Make sure you use the latest version of the colab link/ipynb.
