### ISSUE TITLE
 Request to Add More Extensions as Options

### ISSUE THREAD

**Issue by Orbimac** [etherealxx/volatile-concentration-localux-colab#16]
Dear Ether,

 First and foremost, I would like to express my sincere gratitude for the incredible colab notebook you have provided. Your efforts are truly commendable, and I cannot thank you enough. You are a genius

I am kindly requesting you to  add a few extensions as options, Here are the details:

1. SD WebUI Cutoff: You can find this extension at 

https://github.com/hnmr293/sd-webui-cutoff

2. SD WebUI Infinite Image Browsing: This extension, available at 

https://github.com/zanllp/sd-webui-infinite-image-browsing

3. Ultimate Upscale for Automatic1111: The extension available at 

https://github.com/Coyote-A/ultimate-upscale-for-automatic1111

4. Adetailer: The extension available at

https://github.com/Bing-su/adetailer

Warm regards,
Orbimac

**Comment by etherealxx** [comment]
Hi, @Orbimac 👋

Thanks for using my colab! It's a simple one but i'm glad it helps people that are using it😁

By the way, your wish is granted🎉 (make sure to use the latest July 10 update of the colab)
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/c657fe51-7aae-457c-927b-c9f9e97569b5)

Currently, i just add these extensions straight away. In the future, i might choose which extensions will get added, since too many selectable extensions would be confusing for beginners using the colab.
(i don't quite understand how adetailer works😆)

Please contact me again if found any bugs on the newest version. Have a nice day😋
