### ISSUE TITLE
[Bug]: Adetailer error?

### ISSUE THREAD

**Issue by FxyDreamer** [etherealxx/volatile-concentration-localux-colab#19]
Hi!, adetailer suddenly stopped working, It only generates the image but without the use of adetailer, I read that it should be updated to the "latest version of web-ui" but I can't do it in this google colab, how could I solve this? Appreciate your help

**Comment by etherealxx** [comment]
i need to ask several questions:
- which repo branch you're using? (lite/stable/nightly)
- when was the last time (date and time) you did use adetailer in this colab and works fine?

**Comment by FxyDreamer** [comment]
> i need to ask several questions:
> 
>     * which repo branch you're using? (lite/stable/nightly)
> 
>     * when was the last time (date and time) you did use adetailer in this colab and works fine?

always use "stable", 16 of july at 5:39, (from this moment it stopped working), I tried using it once in "nightly" but I had no result either.

**Comment by etherealxx** [comment]
okay, i need you to test this (since idk how adetailer works)

before running the main cell, go to the debug area, find this cell, change `dev4` to `dev5`, and then run that cell. After done, run the main cell like normal. See if it fixes the adetailer problem.
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/07950bbf-7afe-4fdf-a0cc-5062d0f83cd2)

(for context it rollbacks the adetailer version before july 16th)

**Comment by FxyDreamer** [comment]
> okay, i need you to test this (since idk how adetailer works)
> 
> before running the main cell, go to the debug area, find this cell, change `dev4` to `dev5`, and then run that cell. After done, run the main cell like normal. See if it fixes the adetailer problem. ![image](https://user-images.githubusercontent.com/64251396/254462935-07950bbf-7afe-4fdf-a0cc-5062d0f83cd2.png)
> 
> (for context it rollbacks the adetailer version before july 16th)

thank you! the adetailer problem had already been solved yesterday but I'll keep it in mind in case it fails again
