### ISSUE TITLE
Something went wrong Unexpected end of JSON input

### ISSUE THREAD

**Issue by vinMoreiraHenrique** [etherealxx/volatile-concentration-localux-colab#34]
When i click the big orange "use model" button, it shows this error message: "Something went wrong
Unexpected end of JSON input"

**Comment by just-shinya** [comment]
same here v.v

**Comment by etherealxx** [comment]
working on it!

**Comment by etherealxx** [comment]
Hi @vinMoreiraHenrique, @just-shinya👋 I fixed the error by bumping the gradio version to 3.37.0. Please check the latest August 12 version and close this issue if the problem is solved🙏

https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb
